### ISSUE TITLE
data-crcinit-loadcif or data-CRCInit.loadCIF

### ISSUE THREAD

**Issue by drossner** [cubbles/cubbles-coder-devtools#1]
The grunt task "_createWebpackageDemo" generates a webpackage containing the 'elem-one' elementary. The demo 'index.html' uses the attribute 'data-CRCInit.loadCIF' while all other grunt tasks lead to data-crcinit-loadcif. 

Not sure if this is a "real" issue.

Greets

**Comment by drossner** [comment]
```
var attributeName = 'data-CRCInit.loadCIF';
var loadCIFAttr = crcLoaderElement.getAttribute(attributeName);
attributeName = 'data-crcinit-loadcif';
loadCIFAttr = loadCIFAttr || crcLoaderElement.getAttribute(attributeName);
var defaultValue = 'true';
var loadCIF = loadCIFAttr || defaultValue;
```

**Comment by jtrs** [comment]
This is a bug without serious effects. We renamed the attribut 'data-CRCInit.loadCIF' to 'data-crcinit-loadcif', but because of downwards compatability works 'data-CRCInit.loadCIF' too. But the generator should create the new attribute.
Created a new Issue https://cubbles.atlassian.net/browse/CDT-15

**Comment by drossner** [comment]
Further question:
main.js:125 Expected CRCLoader attribute "data-crcinit-loadcif" to be "true" or "false". Got "true". Going to use default value "true".

This warning appears for: ="true" and ="false", it does not appear for =0 or =1 or if i do not set this attr at all.
